# 
# Do not Edit! Generated by:
# spectacle version 0.18
# 
# >> macros
# << macros

Name:       rockmarble
Summary:    Follow your favourite artists tour around the world
Version:    0.6.1
Release:    1
Group:      Applications/Internet
License:    GPLv2+
URL:        http://rockmarble.sourceforge.net
Source0:    %{name}-%{version}.tar.bz2
Source100:  rockmarble.yaml
Requires(post): /bin/touch
Requires(post): gtk2
Requires:  	qjson
BuildRequires:  pkgconfig(QtCore) >= 4.6.0
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  qjson-devel
BuildRequires:  desktop-file-utils


%description
rockmarble is a simple program that fetches artist tour dates from last.fm and shows the event location using marble



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
qmake PREFIX=%{_prefix}
# << build pre



# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
make INSTALL_ROOT=%{buildroot} install
#make INSTALL_ROOT=%{buildroot}/usr install
# << install post
desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop



%post
/bin/touch --no-create %{_datadir}/icons/hicolor || :
%{_bindir}/gtk-update-icon-cache \
  --quiet %{_datadir}/icons/hicolor 2> /dev/null|| :

%postun
/bin/touch --no-create %{_datadir}/icons/hicolor || :
%{_bindir}/gtk-update-icon-cache \
  --quiet %{_datadir}/icons/hicolor 2> /dev/null|| :


%files
%defattr(-,root,root,-)
%{_bindir}/rockmarble
%{_datadir}/applications/*.desktop
%{_datadir}/icons/hicolor/64x64/apps/rockmarble.png
# >> files
# << files


